version: '3.8'

services:
  importer-expenses:
    build: ./src/importer-old-expenses

  api:
    build: ./src/Terminus/API
    ports:
      - '5001:5001'
    depends_on:
      - db

  db:
    build: ./src/database
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"